import argparse
import datetime
import os
import subprocess


def generateFileFromSchema() -> None:
    """Generate pydantic file from xsd file with a parser."""
    p = argparse.ArgumentParser(
        description="Generate schema from schema.xsd file"
    )
    p.add_argument(
        "-s",
        "--schemaFile",
        dest="schemaFile",
        type=str,
        default="./schema.xsd",
        help="Filepath to GEOS schema file.",
    )
    p.add_argument(
        "-cf",
        "--configFile",
        dest="configFile",
        type=str,
        default="./config_schema.xml",
        help="Filepath to xml configuration file for schema generation.",
    )
    p.add_argument(
        "-v",
        "--version",
        dest="version",
        type=str,
        default="",
        help="GEOS commit sha or version identification.",
    )

    pp, _ = p.parse_known_args()

    run_process_Xsdata(pp.schemaFile, pp.configFile)
    addHeader(pp.version)
    cleanInit()


def run_process_Xsdata(schemaXSDFile: str, XmlConfigFile: str) -> None:
    """Launch the subprocess that run xsdata-pydantic to generate the file from the schema XSD file.

    Args:
        schemaXSDFile(str): Filepath to GEOS XSD file.
        XmlConfigFile(str): Filepath to xsdata configuration file.

    Raises:
        RuntimeError: Error encountered during the subprocess run.
    """
    result = subprocess.Popen(
        [
            "xsdata",
            "generate",
            schemaXSDFile,
            "--config",
            XmlConfigFile,
        ],
    )
    if result.wait() != 0:
        raise RuntimeError(
            "Something went wrong with the schema generation. Please check parameters."
        )


def cleanInit() -> None:
    """Manually clean the modifications to __init__ files done during xsdata process."""
    root: str = os.getcwd()

    for dirpath, _, filenames in os.walk(root):
        if "__init__.py" in filenames:
            init_file = os.path.join(dirpath, "__init__.py")
            with open(init_file, "w") as f:
                f.write("")
            print(f"Cleaned {init_file}")


def addHeader(
    sha: str = "", generatedSchemaFile: str = "schema_mod.py"
) -> None:
    """Manually insert a header containing datetime information and GEOS commit version if provided to the file generated by xsdata previously.

    Args:
        sha(str, optional): commit sha or GEOS version. Default is empty string.
        generatedSchemaFile(str, optional): Name of the file generated.
    """
    head: str = f"""#------------------------------------------------------------------
#
#  Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}
#  GEOS version: {sha}
#
#-------------------------------------------------------------------\n\n
# ruff:noqa\n"""

    try:
        with open(generatedSchemaFile, "r") as f:
            schema: str = f.read()

        with open(generatedSchemaFile, "w") as g:
            g.write(head)
            g.write(schema)

    except Exception as e:
        print(e)


if __name__ == "__main__":
    generateFileFromSchema()
