"""
Entry point for debugging geos-ats

To use this script, do the following:
- Setup your ats environment (using the 'make ats_environment' command)
- Create a copy of this script in the build/integratedTests directory
- Debug this script with a tool like vscode

Note: if you have a copy of the geosPythonPackages repository located
in your user workspace, then this script will attempt to use that version
of geos_ats instead of the one installed in your environment.
"""

import os
import sys


def debug_geos_ats():
    # Check for a copy of geos_ats in the user's workspace to use
    # instead of any currently installed in python
    user = os.environ.get( 'USER', '' )
    mod_path = f"/usr/workspace/{user}/geosPythonPackages/geos-ats"
    if os.path.isdir( mod_path ):
        sys.path.insert( 0, os.path.join( mod_path ) )

    # Collect command line args from autogenerated script
    fname = os.path.join( os.path.dirname( __file__ ), 'geos_ats.sh' )
    args = open( fname, 'r' ).readlines()[ 1 ].split()[ 1:-1 ]
    sys.argv.extend( args )

    # Run ats
    from geos.ats import main
    main.main()


if __name__ == '__main__':
    debug_geos_ats()
