[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# [tool.setuptools]
# packages = ["geos-ats", "geos-ats.helpers", "geos-ats.assets", "geos-ats.machines"]

[project]
name = "geos-ats"
version = "0.2.0"
description = "ATS implementation for GEOS testing"
authors = [{name = "GEOS Contributors" }]
maintainers = [
    {name = "sherman", email = "sherman27@llnl.gov"}
]
license = {text = "LGPL-2.1"}
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

requires-python = ">=3.7"
    
dependencies = [
    "h5py",
    "mpi4py",
    "numpy",
    "lxml",
    "tabulate",
    "pyyaml",
    "tqdm",
    "requests",
    "GitPython",
    "google-cloud-storage",
    "pip-system-certs",
    "ats @ https://github.com/LLNL/ATS/archive/refs/tags/7.0.105.tar.gz",
]

[tool.setuptools.package-data]
myModule = ["*.js", "*.css", "*.zip"]

[project.scripts]
    run_geos_ats = "geos.ats.main:main"
    setup_ats_environment = "geos.ats.environment_setup:main"
    geos_ats_log_check = "geos_ats.helpers.log_check:main"
    geos_ats_restart_check = "geos_ats.helpers.restart_check:main"
    geos_ats_curve_check = "geos_ats.helpers.curve_check:main"

[project.urls]
Homepage = "https://github.com/GEOS-DEV/geosPythonPackages"
Documentation = "https://geosx-geosx.readthedocs-hosted.com/projects/geosx-geospythonpackages/en/latest/"
Repository = "https://github.com/GEOS-DEV/geosPythonPackages.git"
"Bug Tracker" = "https://github.com/GEOS-DEV/geosPythonPackages/issues"

