[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geos-xml-tools"
version = "0.6.0"
description = "Tools for enabling advanced xml features in GEOSX"
maintainers = [
    {name = "Christopher Sherman", email = "sherman27@llnl.gov" }
]
license = {text = "LGPL-2.1"}

requires-python = ">=3.8"

dependencies = [
    "lxml>=4.5.0",
    "parameterized",
    "numpy"
]

[project.scripts]
    preprocess_xml = "geos.xml_tools.main:preprocess_serial"
    format_xml = "geos.xml_tools.xml_formatter:main"
    test_geosx_xml_tools = "geos.xml_tools.tests.test_manager:main"
    check_xml_attribute_coverage = "geos.xml_tools.attribute_coverage:main"
    check_xml_redundancy = "geos.xml_tools.xml_redundancy_check:main"

[tool.mypy]
# Specify the target platform details in config, so your developers are
# free to run mypy on Windows, Linux, or macOS and get consistent
# results.
python_version = "3.10"
#exclude = [] 
# strict = true

warn_unreachable = true
implicit_reexport = true
show_error_codes = true
show_column_numbers = true
ignore_missing_imports = true
warn_unused_configs = true

# Overrides for currently untyped modules
[[tool.mypy.overrides]]
module = [
    "tests.*",
]
ignore_errors = true
