name: "Pull Request Docs Check"
on: 
- pull_request

# Cancels in-progress workflows for a PR when updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@dev
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html . _build -W"
