name: "Pull Request Typing Check"
on: 
- pull_request

# Cancels in-progress workflows for a PR when updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        # add packages to check typing
        package-name: ["geos-posp", "geos-timehistory", "geos-utils", "geos-xml-tools", "hdf5-wrapper"]

    steps:
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install package
      # working-directory: ./${{ matrix.package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        python -m pip install ./${{ matrix.package-name }}/

    - name: Typing check with mypy
      #  working-directory: ./${{ matrix.package-name }}
      run:  |
        python -m mypy --config-file ./.mypy.ini --check-untyped-defs ./${{ matrix.package-name }}
