name: "Pull Request Typing Check"
on: 
- pull_request

# Cancels in-progress workflows for a PR when updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        # add packages to check typing
        package-name: ["geos-geomechanics", "geos-posp", "geos-timehistory", "geos-utils", "geos-xml-tools", "hdf5-wrapper"]

    steps:
    - uses: actions/checkout@v4
    - uses: mpi4py/setup-mpi@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install package
      # working-directory: ./${{ matrix.package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy ruff

    - name: Typing check with mypy
      #  working-directory: ./${{ matrix.package-name }}
      run:  |
        python -m mypy --config-file ./.mypy.ini --check-untyped-defs ./${{ matrix.package-name }}

    - name: Format and linting check with ruff
      #  working-directory: ./${{ matrix.package-name }}
      run:  |
        python -m ruff check --config .ruff.toml ./${{ matrix.package-name }}