name: "Pull Request Typing Check"
on: 
- pull_request

# Cancels in-progress workflows for a PR when updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        # add packages to check typing
        package-name: ["geos-posp", "geos-timehistory", "geos-utils", "geos-xml-tools", "hdf5-wrapper"]

    steps:
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install package
      # working-directory: ./${{ matrix.package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy ruff

    - name: Typing check with mypy
      #  working-directory: ./${{ matrix.package-name }}
      run:  |
        python -m mypy --config-file ./.mypy.ini --exclude 'build' --check-untyped-defs ./${{ matrix.package-name }}

    # Removed that 'ruff' run for the moment because it would created conflicts with 'mypy' when solving an error thrown
    # by 'ruff', and the reverse situation was the same ...
    # 'mypy' checking works great, let's keep that
    # A dedicated PR for the 'ruff' checking in the geosPythonPackages would be required

    # - name: Format and linting check with ruff
      #  working-directory: ./${{ matrix.package-name }}
      # run:  |
      #   python -m ruff check --config .ruff.toml ./geos-utils
